### ISSUE TITLE
Have distinct XMPP domain names

### ISSUE THREAD

**Issue by guusdk** [surevine/openfire-docker-compose#1]
Although each server starts with a different hostname (`xmpp1.localhost.example` and `xmpp1.localhost.example`) they're both identifying themselves using the same XMPP domain name value (`localhost.example`). These should be two different values. We have a couple of options, but making the XMPP domain equal to the hostname is convenient for configuring clients (unless we also want to put DNS SRV records in place).

**Comment by viv** [comment]
The PR sets the XMPP domains to the same as the hostname:

- xmpp1.localhost.example
- xmpp2.localhost.example
