### ISSUE TITLE
Adapt or clone for clustering

### ISSUE THREAD

**Issue by guusdk** [surevine/openfire-docker-compose#16]
The content of this repository is very handy for establishing an environment that consists of two distinct XMPP domains, that can be used to test functionality that relates to 'federation'.

It would be helpful to have a similar solution that establishes an Openfire cluster (one XMPP domain, that consists of two distinct servers). I'm not sure if it makes sense to add that functionality to this repository, or simply create a new solution/repo altogether.

Obvious differences between the desired clustering environment and a federation environment:

- In clustering, each host uses the same XMPP Domain name value. The fully qualified hostname for each server can be distinct.
- The network between the hosts ideally allows for multicast traffic between them, on IP Address: 224.2.2.3 UDP Port: 54327 
- The Hazelcast plugin is needed on both Openfire nodes. If multicast is available as defined above, I don't think it requires further configuration? If UDP can't be used, TCP can be used. See https://www.igniterealtime.org/projects/openfire/plugins/2.4.2/hazelcast/readme.html#config
- all instances of Openfire share the same database.

**Comment by Fishbowler** [comment]
This will be useful for testing, e.g. proving the fix for https://igniterealtime.atlassian.net/browse/OF-2077, and having an environment to prevent similar issues in the future.
