### ISSUE TITLE
Allow a non-docker host to federate

### ISSUE THREAD

**Issue by guusdk** [surevine/openfire-docker-compose#6]
It would speed up development time if we were able to run one Openfire instance outside of the docker compose based environment, at times. That would allow, for example, to run one Openfire in a debugger, while we're sending FMUC data from the other.

I'm not exactly sure what would be needed, but most if it revolves around having networking / name resolution, I think? Maybe exposing port 5269 (for s2s) combined with some editing of `/etc/hosts` files suffices.

**Comment by viv** [comment]
That PR exposes the S2S ports to your local machine (on non standard ports). The container-based Openfire(s) can access your local Openfire on host.docker.internal

https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
